### ISSUE TITLE
Problem with aggregate function

### ISSUE THREAD

**Issue by davittorosyan** [verkhoumov/codeigniter-mongodb-library#16]
Hi,
I'm using  this call:

`$this->mongo_db->aggregate('orders', ['$project' => ['cusip' => 1, 'date' => 1, 'price' => 1, '_id' => 0 ]], ['allowDiskUse' => TRUE]);`

But get this error, looks like aggregate function don't working correctly... 

[Mongo_db::aggregate(): Failed to complete following command: wrong type for field (pipeline) 3 != 4](url)

or maybe i did something wrong?

**Comment by verkhoumov** [comment]
Hi, @davittorosyan! May you show me your code of aggregate query?

I think that the error is an example and you should use the following query variant:
```php
$this->mongo_db->aggregate('orders', 
	[
		[
			'$project' => [
				'cusip' => 1, 
				'date' => 1, 
				'price' => 1, 
				'_id' => 0
			]
		]
	], 
	[
		'allowDiskUse' => TRUE
	]
);
```

Here it is shown how to correctly:
https://stackoverflow.com/questions/14131833/mongodb-aggregate-query-using-php-driver

**Comment by davittorosyan** [comment]
Hi @verkhoumov , 
thanks a lot for your true example, this help us very much.
You have great library.
