### ISSUE TITLE
Error in Aggregate function

### ISSUE THREAD

**Issue by mullernato** [verkhoumov/codeigniter-mongodb-library#17]
Using the aggregate function as this return a error:
```
$r = $this->mongo_db->aggregate(
                    'users',
                    [
                        '$match' => ['username' => 'anyuser']
                    ]
                );
```
or as this in the Wiki page
```
$result = $this->mongo_db->aggregate(
    'stocks',
    [
        '$project' => [
            'cusip' => 1, 
            'date'  => 1, 
            'price' => 1, 
            '_id'   => 0 
        ]
    ],
    [
        'allowDiskUse' => TRUE
    ]
);
```
> Mongo_db::aggregate(): Failed to complete following command: 'pipeline' option must be specified as an array

if I use with array in the pipeline:
```
$r = $this->mongo_db->aggregate(
                    'users',
                    [
                        ['$match' => ['username' => 'anyuser']]
                    ]
                );
```
this return:
> Mongo_db::aggregate(): Failed to complete following command: The 'cursor' option is required, except for aggregate with the explain argument

**Comment by mullernato** [comment]
To solve this add 
`['cursor' => ['batchSize' => 0]]`
In options area.
and change the example Wiki to:
```
$result = $this->mongo_db->aggregate(
    'stocks',
    [
        ['$project' => [
            'cusip' => 1, 
            'date'  => 1, 
            'price' => 1, 
            '_id'   => 0 
        ]]
    ],
    [
        'allowDiskUse' => TRUE,
        'cursor' => ['batchSize' => 0]
    ]
);
```
Please add this information on Wiki. ;)

**Comment by verkhoumov** [comment]
Dear @mullernato, what version of MongoDB do you use? Beginning with version 3.6, you need to specify the `cursor` option.

**Comment by verkhoumov** [comment]
Wiki fixed!
