### ISSUE TITLE
Error from Aggregate Query: Undefined property: Mongo_db::$read_preference

### ISSUE THREAD

**Issue by bthart** [verkhoumov/codeigniter-mongodb-library#18]
Hi,

When running an aggregate query, I am getting the following error. It is the second query i am running on the same page. I can't seem to get rid of this error. Any ideas?

A PHP Error was encountered
Severity: Notice
Message: Undefined property: Mongo_db::$read_preference
Filename: libraries/Mongo_db.php
Line Number: 3943

Thanks!
Brian

**Comment by verkhoumov** [comment]
Hi, @bthart! Update library to the last version. It’s error was been already fixed!
