### ISSUE TITLE
Default value in method row_array() for parameter $n with a integer type hint can only be NULL

### ISSUE THREAD

**Issue by wisnubaldas** [verkhoumov/codeigniter-mongodb-library#3]
hi, im tray using this library and have this error
`
Fatal error: Default value for parameters with a class type can only be NULL in /var/www/html/web/application/libraries/Mongo_db.php on line 4549
A PHP Error was encountered
Severity: Compile Error
Message: Default value for parameters with a class type can only be NULL
Filename: libraries/Mongo_db.php
Line Number: 4549
Backtrace:
`
this my mongo config
![config](https://user-images.githubusercontent.com/10908214/31042007-d766c73e-a5c8-11e7-856e-906c20e11893.png)

**Comment by verkhoumov** [comment]
@wisnubaldas, thank you very much! Fixed it! The problem is not with the connection itself, but with the use of method row_array(). I apologize for having done this only 4 days later.
