### ISSUE TITLE
Namespace MongoDB\Driver\Command hadn't included

### ISSUE THREAD

**Issue by wisnubaldas** [verkhoumov/codeigniter-mongodb-library#5]
hi, sorry again, i tried to use agregate on your library, here is my collection list:
send_arrival collection:
{ 
    "_id" : ObjectId("59e0985efffca4607a31550e"), 
    "tracking_number" : "ID1900432071", 
    "status" : "arrived", 
    "status_date" : "2017-10-04 13:46:29", 
    "time_sending" : "2017-10-12 18:41:33", 
    "flag" : "cloud"
}

send_bc_success collection:
{
    "_id": ObjectId ("59e09cc0fffca467a0361f96"),
    "tracking_number": "ID1900432071",
    "status": "import_custom_clearance_success",
    "status_date": "2017-10-05 22:18:53",
    "time_sending": "2017-10-12 19:00:14",
    "flag": "lazada"
}

and I try to join with aggregate:
$ result = $ this-> mongo_db-> aggregate (
'send_arrival',
[
['$ sort' => ["tracking_number" => -1]],
['$ lookup' => [
"localField" => "tracking_number",
"from" => "send_arrival",
"foreignField" => "tracking_number",
"as" => "send_bc_success"
]],
'$ project' => [
"tracking_number" => 1,
"status" => 1,
"send_bc_success.tracking_number" => 1,
"send_bc_success.status" => 1,
"_id" => 0
],

],
[
'allowDiskUse' => TRUE
]
);
the output generated is always error, is there any error in my script? the error I get is:
Type: Error

Message: Class 'Command' not found

Filename: /home/wisnu/web/gtln/application/libraries/Mongo_db.php

Line Number: 3942

**Comment by verkhoumov** [comment]
Hi, @wisnubaldas! Sorry about it! Apparently, I forgot to add the corresponding namespace (MongoDB\Driver\Command), so execute of commands and aggregation hadn't worked. Update library to v1.1.0.
